/*
 * Pull the three faces the 3.x design asks for into the repo.
 *
 * This is a desktop app, so a font cannot be a network request at runtime: a
 * machine with no connection would fall back to Segoe UI and the whole type
 * system would be gone with it. Run once, commit what lands, and re-run only
 * to take an upstream revision.
 *
 * Two things this has to get right, both of which cost a run to discover:
 *
 * - Fontshare answers a request for one family with several. Asking for
 *   `cabinet-grotesk` also returns General Sans, so the response is filtered
 *   against the list below rather than trusted.
 * - Google serves one @font-face per unicode subset, six for Geist Mono, all
 *   with the same family and weight. Writing them by family and weight alone
 *   put six different files at one path and kept the last. Each subset keeps
 *   its own file and its own `unicode-range`, which is the whole point of the
 *   split: a run of Latin text downloads 6 KB rather than 70.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const OUT = 'src/renderer/src/assets/fonts';
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

/** Only these families are kept, whatever the endpoint decides to send. */
const WANTED = new Set(['Cabinet Grotesk', 'Satoshi', 'Geist Mono']);

const SOURCES = [
  'https://api.fontshare.com/v2/css?f%5B%5D=cabinet-grotesk@500,700&display=swap',
  'https://api.fontshare.com/v2/css?f%5B%5D=satoshi@400,500,700&display=swap',
  'https://fonts.googleapis.com/css2?family=Geist+Mono:wght@400;500&display=swap',
];

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

await mkdir(OUT, { recursive: true });

const faces = [];
const seen = new Map();

for (const url of SOURCES) {
  const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();
  for (const block of css.split('@font-face').slice(1)) {
    const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
    if (!family || !WANTED.has(family)) continue;

    const weight = /font-weight:\s*(\d+)/.exec(block)?.[1];
    const style = /font-style:\s*(\w+)/.exec(block)?.[1] ?? 'normal';
    const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim();
    // woff2 only. The woff and ttf alternatives are the same glyphs, larger.
    const src = /url\((['"]?)(\/\/|https?:\/\/)([^'")]+\.woff2)\1\)/.exec(block);
    if (!weight || !src) continue;

    const key = `${family} ${weight} ${style}`;
    const nth = (seen.get(key) ?? 0) + 1;
    seen.set(key, nth);

    const file = `${slug(family)}-${weight}${nth > 1 || range ? `-${nth}` : ''}.woff2`;
    const bytes = Buffer.from(
      await (await fetch('https://' + src[3], { headers: { 'User-Agent': UA } })).arrayBuffer(),
    );
    await writeFile(join(OUT, file), bytes);
    faces.push({ family, weight, style, range, file, size: bytes.length });
    console.log(`  ${family} ${weight}  ${file}  ${(bytes.length / 1024).toFixed(1)} KB`);
  }
}

const header = `/*
 * The three faces of 3.x, bundled.
 *
 * Bundled rather than fetched: GoodBit runs on a machine that may have no
 * connection, and a CDN link would silently drop the whole type system back
 * to Segoe UI. \`font-display: block\` for the same reason, since there is no
 * network to wait on and a swap would only flash.
 *
 * Cabinet Grotesk and Satoshi: Indian Type Foundry, ITF Free Font License.
 * Geist Mono: Vercel, SIL Open Font License 1.1.
 *
 * Generated by \`node scripts/fetch-fonts.mjs\`. Do not edit by hand.
 */
`;

const body = faces
  .map((f) =>
    [
      '@font-face {',
      `  font-family: '${f.family}';`,
      `  src: url('./assets/fonts/${f.file}') format('woff2');`,
      `  font-weight: ${f.weight};`,
      `  font-style: ${f.style};`,
      '  font-display: block;',
      ...(f.range ? [`  unicode-range: ${f.range};`] : []),
      '}',
    ].join('\n'),
  )
  .join('\n\n');

await writeFile('src/renderer/src/fonts.css', header + '\n' + body + '\n', 'utf8');
console.log(`\n${faces.length} faces, ${(faces.reduce((a, f) => a + f.size, 0) / 1024).toFixed(0)} KB total`);
